"""add source_type and attribution to articles

Revision ID: f3f21c56d430
Revises: 880d4f435f08
Create Date: 2026-04-12 09:45:52.051475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3f21c56d430'
down_revision: Union[str, Sequence[str], None] = '880d4f435f08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('attribution', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('attribution')
        batch_op.drop_column('source_type')

    # ### end Alembic commands ###
